# Generated by Django 3.1 on 2021-07-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imgge',
            new_name='Image',
        ),
    ]
